export const actionType = {
  SET_QUERY: 'SET_QUERY',
  RESET_QUERY: 'RESET_QUERY',
  NEXT_PAGE: 'NEXT_PAGE',
  GET_IMAGES: 'GET_IMAGES',
  GET_TOTAL: 'GET_TOTAL',
  LOADING_START: 'LOADING_START',
  LOADING_END: 'LOADING_END',
  SET_IMG_URL: 'SET_IMG_URL',
};
